name: CI
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        mode:
          - cgo
          - tinygo
          - wazero
        os:
          - macos-12
          - ubuntu-22.04
          - windows-2022
        exclude:
          - os: windows-2022
            mode: cgo
          # https://github.com/tinygo-org/tinygo/issues/3594
          - os: windows-2022
            mode: tinygo
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.8'
          cache: true

      - name: setup re2 for cgo (linux)
        if: ${{ startsWith(matrix.os, 'ubuntu-') && matrix.mode == 'cgo' }}
        run: sudo apt-get update && sudo apt-get install -y libre2-dev
      - name: setup re2 for cgo (mac)
        if: ${{ startsWith(matrix.os, 'macos-') && matrix.mode == 'cgo' }}
        run: brew install re2

      - name: setup tinygo
        if: ${{ matrix.mode == 'tinygo' }}
        uses: acifani/setup-tinygo@v1
        with:
          tinygo-version: 0.27.0
      - name: setup wasmtime for tinygo
        if: ${{ matrix.mode == 'tinygo' }}
        run: go install github.com/wasilibs/tools/cmd/wasmtime@c93d2e477ab3c1eb7f5303c66a35c84a21d06dbd

      - run: go run mage.go check
        env:
          RE2_TEST_MODE: ${{ matrix.mode }}
          # General coverage should be good enough to not need to slow down development
          # on these slow tests.
          RE2_TEST_EXHAUSTIVE: ${{ github.event_name != 'pull_request' && '1' || '0'}}
          # Windows runner seems to not have enough CPU performance to keep up without a memory limit
          GOMEMLIMIT: ${{ (github.event_name != 'pull_request' && matrix.os == 'windows-2022') && '1GiB' || '' }}

  # Runs tests using wazero inside a minimal golang docker image. This makes sure the code builds
  # even when there is no C toolchain available. It is possible for code to work fine with CGO_ENABLED=0
  # but not build without a C toolchain available, e.g. if C source files are checked into the repo
  # without a build tag to exclude them from pure-Go builds.
  docker-build:
    runs-on: ubuntu-22.04
    container:
      image: golang:alpine
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: if command -v gcc &> /dev/null; then echo "GCC found but not expected"; exit 321; fi

      - run: go run mage.go test
