name: Go Dependabot PR Workspace Sync

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  sync:
    uses: curioswitch/go-build/.github/workflows/export-dependabot-go-sync.yaml@11b22f19dd2fa2a8bcf50a89a33011764dde35fe
    with:
      github_app_id: ${{ vars.WASILIBS_APP_ID }}
    secrets:
      github_app_key: ${{ secrets.WASILIBS_APP_PRIVATE_KEY }}
